---
# BOSH Director must have Cloud Config with the following properties:
# - vm_type: tiny
# - network: manual

name: ((deployment_name))

releases:
- name: dummy
  url: https://github.com/pivotal-cf-experimental/dummy-boshrelease/releases/download/v2/dummy-2.tgz
  version: 2

stemcells:
- alias: ubuntu
  os: ubuntu-trusty
  version: latest

instance_groups:
- name: dummy
  instances: 1
  vm_type: default
  stemcell: ubuntu
  networks:
  - name: default
  jobs:
  - name: dummy
    release: dummy

update:
  canaries: 1
  max_in_flight: 6
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
